/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * NewJFrame.java
 *
 * Created on 18-nov-2011, 21:02:25
 */

package ui;

import java.io.File;
import java.util.ArrayList;

import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.event.TreeSelectionEvent;
import javax.swing.event.TreeSelectionListener;
import javax.swing.tree.DefaultMutableTreeNode;
import javax.swing.tree.DefaultTreeModel;

import reader.Reader;
import world.World;

/**
 *
 * @author Israel
 */
public class StoryJFrame extends javax.swing.JFrame {

    /** Creates new form NewJFrame */
    public StoryJFrame() {
        initComponents();
    }
    
    private DefaultTreeModel model;
    private DefaultMutableTreeNode titleTree;
    private Reader reader = null;

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        createJTree();
        jScrollPane2 = new javax.swing.JScrollPane();
        textAreaVisualizacion = new javax.swing.JTextArea();
        labelVisualizacion = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        menuArchivo = new javax.swing.JMenu();
        menuItemArchivo = new javax.swing.JMenuItem();
        menuItemSalir = new javax.swing.JMenuItem();
        menuGeneracion = new javax.swing.JMenu();
        menuItemSiguiente = new javax.swing.JMenuItem();
        menuItemCompleta = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        //jScrollPane1.setViewportView(treeViewer);

        textAreaVisualizacion.setColumns(20);
        textAreaVisualizacion.setRows(5);
        textAreaVisualizacion.setFont(new java.awt.Font("Garamond", 0, 18));
        jScrollPane2.setViewportView(textAreaVisualizacion);

        labelVisualizacion.setFont(new java.awt.Font("Garamond", 0, 18)); // NOI18N
        labelVisualizacion.setText("Visualización de selección:");
        labelVisualizacion.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        menuArchivo.setText("Archivo");

        menuItemArchivo.setText("Comenzar desde archivo");
        menuItemArchivo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                menuItemArchivoMouseClicked(evt);
            }
        });
        menuArchivo.add(menuItemArchivo);

        menuItemSalir.setText("Salir");
        menuItemSalir.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                menuItemSalirMouseClicked(evt);
            }
        });
        menuArchivo.add(menuItemSalir);

        jMenuBar1.add(menuArchivo);

        menuGeneracion.setText("Generación");
        
        menuItemSiguiente.setText("Siguiente segmento");
        menuItemSiguiente.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                menuItemSiguienteMouseClicked(evt);
            }
        });
        
        menuGeneracion.add(menuItemSiguiente);

        menuItemCompleta.setText("Completa");
        menuItemCompleta.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                menuItemCompletaMouseClicked(evt);
            }
        });
        
        menuGeneracion.add(menuItemCompleta);
        

        jMenuBar1.add(menuGeneracion);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 206, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 599, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelVisualizacion, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(labelVisualizacion, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 285, Short.MAX_VALUE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 312, Short.MAX_VALUE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    private void createJTree() {
    	titleTree = new DefaultMutableTreeNode("Mito");
        model = new DefaultTreeModel(titleTree);
        treeViewer = new javax.swing.JTree(model);
        treeViewer.addTreeSelectionListener(new TreeSelectionListener() {
            public void valueChanged(TreeSelectionEvent e) {
                DefaultMutableTreeNode node = (DefaultMutableTreeNode)
                                   treeViewer.getLastSelectedPathComponent();

                if (node == null) return;

                int depthLevel = node.getLevel();
                
                switch (depthLevel) {
                case 1:
                	// Es un segmento
                	StoryMutableTreeNode segment = (StoryMutableTreeNode) node;
                	String segmentContent = reader.getStorySoFar().get(segment.getSegmentPosition()).toStringSegment();
                	textAreaVisualizacion.setText(segmentContent);
                	break;
                case 2:
                	// Es una relación
                	StoryMutableTreeNode relation = (StoryMutableTreeNode) node;
                	String relationContent = reader.getStorySoFar().get(relation.getSegmentPosition()).getComponent(relation.getRelationPosition()).toStringRelation();
                	textAreaVisualizacion.setText(relationContent);
                	break;
                }
                               
            }
        });
        
        jScrollPane1.setViewportView(treeViewer);
    }
    
    private void insertStory(ArrayList<World> story) {
    	for (int i = 0; i < story.size(); i++) {
        	StoryMutableTreeNode segment = new StoryMutableTreeNode("Segmento "+i,i);
        	model.insertNodeInto(segment, titleTree, i);
        	for (int j = 0; j < story.get(i).getNumComponents(); j++) {
        		StoryMutableTreeNode relation = new StoryMutableTreeNode("Relación "+j,i,j);
        		model.insertNodeInto(relation, segment, j);
        	}
        }
    }

    private void menuItemSiguienteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menuItemSiguienteMouseClicked
    	if ((reader != null) && reader.isInitialized()) {
	    	createJTree();
	        insertStory(reader.generateNextSegment());
	        model.reload();
    	}
        else {
        	JOptionPane.showMessageDialog(null, "La historia no ha sido inicializada. Escoge un archivo para inicializar.");
        }
    }//GEN-LAST:event_menuItemSiguienteMouseClicked
    
    private void menuItemCompletaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menuItemCompletaMouseClicked
        if ((reader != null) && reader.isInitialized()) {
	    	createJTree();
	        insertStory(reader.generateStory());
	        model.reload();
        }
        else {
        	JOptionPane.showMessageDialog(null, "La historia no ha sido inicializada. Escoge un archivo para inicializar.");
        }
    }//GEN-LAST:event_menuItemCompletaMouseClicked

    private void menuItemArchivoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menuItemArchivoMouseClicked
        // TODO add your handling code here:
    	JFileChooser fc = new JFileChooser();
    	int returnVal = fc.showOpenDialog(this);

        if (returnVal == JFileChooser.APPROVE_OPTION) {
            File file = fc.getSelectedFile();
            reader = new Reader();
            reader.createMind(file.getPath());
            createJTree();
            insertStory(reader.getStorySoFar());
	        model.reload();
        }
    }//GEN-LAST:event_menuItemArchivoMouseClicked

    private void menuItemSalirMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menuItemSalirMouseClicked
    	this.dispose();
    }//GEN-LAST:event_menuItemSalirMouseClicked

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
            	StoryJFrame sJF = new StoryJFrame();
                sJF.setTitle("Generador de Historias");
                sJF.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel labelVisualizacion;
    private javax.swing.JMenu menuArchivo;
    private javax.swing.JMenu menuGeneracion;
    private javax.swing.JMenuItem menuItemArchivo;
    private javax.swing.JMenuItem menuItemSiguiente;
    private javax.swing.JMenuItem menuItemCompleta;
    private javax.swing.JMenuItem menuItemSalir;
    private javax.swing.JTextArea textAreaVisualizacion;
    private javax.swing.JTree treeViewer;
    // End of variables declaration//GEN-END:variables

}
